resource_types:
- name: slack_notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/smichard/IoT_demo.git
    branch: master
  check_every: 10s

- name: cloud_foundry
  type: cf
  source:
    api: {{cf_api}}
    username: {{cf_user}}
    password: {{cf_password}}
    organization: {{cf_org}}
    space: {{cf_space}}
    skip_cert_check: false

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/IoT_demo.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.5.0

- name: S3_target
  type: s3
  source:
    endpoint: {{s3_endpoint}}
    bucket: releases
    regexp: release_history/iot_demo-(.*)-(.*).tar.gz
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}

jobs:
  - name: test-app
    public: true

    serial: true
    plan:
      - get: app_sources
        trigger: true
      - task: unit
        file: app_sources/website/ci/tasks/unit.yml

  - name: deploy-app
    public: true
    serial: true
    plan:
    - get: app_sources
      passed: [ test-app ]
      version: every
      trigger: true
    - put: cloud_foundry
      params:
        path: app_sources/website/
        manifest: app_sources/website/manifest.yml
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Dev: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
            https://iotdemocloud.cfapps.io/
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Dev: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID

  - name: ecs-backup
    public: true
    serial: true
    plan:
    - get: version
      trigger: false
    - get: app_sources
      trigger: true
      passed: [ deploy-app ]
    - task: create-artifact
      file: app_sources/website/ci/tasks/create_artifact.yml
    - put: S3_target
      params:
        file: ./artifact/iot_demo-*-*.tar.gz
        acl: public-read

  - name: bump-version-minor
    public: true
    plan:
      - aggregate:
        - get:  app_sources
          passed: [ ecs-backup ]
          trigger: true
        - get: version
          trigger: false
        - put: version
          params: {bump: minor}